const langs = {
    gb: {
        companyName: 'bitjalang',
        Funding: 'Funding',
        in: 'in',
        SignIn: 'Sign In',
        Equity: 'Equity',
        Locked: 'Locked',
        MarginLevel: 'Margin Level',
        Account: 'Account',
        SignOut: 'Sign Out',
        ClientArea: 'Client Area',
        Profile: 'Profile',
        Deposit: 'Deposit',
        Withdrawals: 'Withdrawals',
        Calculator: 'Calculator',
        ProfitLoss: 'Profit/Loss',
        TargetPrice: 'Target Price',
        LiquidationPrice: 'Liquidation Price',
        Side: 'Side',
        Long: 'Long',
        Short: 'Short',
        Amount: 'Amount',
        EntryPrice: 'Entry Price',
        OpenPrice: 'Open Price',
        ClosePrice: 'Close Price',
        CloseTime: 'Time Close',
        Leverage: 'Leverage',
        Margin: 'Margin',
        InitialQuantity: 'Initial Quantity',
        FinalQuantity: 'Final Quantity',
        ROE: 'ROE',
        Cross: 'Cross',
        Isolated: 'Isolated',
        Balance: 'Balance',
        CurrentMargin: 'Current Margin',
        FinalMargin: 'Final Margin',
        Market: 'Market',
        Type: 'Type',
        Price: 'Price',
        Filled: 'Filled',
        Quantity: 'Quantity',
        TimeExecuted: 'Time Executed',
        Status: 'Status',
        Prev: 'Prev',
        Next: 'Next',
        LastTrades: 'Last Trades',
        All: 'All',
        My: 'My',
        Time: 'Time',
        Login: 'Login',
        Password: 'Password',
        Markets: 'Markets',
        Instrument: 'Instrument',
        LastPrice: 'Last Price',
        Change: 'Change',
        Volume: 'Volume',
        NewOrder: 'NewOrder',
        Limit: 'Limit',
        Stop: 'Stop',
        StopPrice: 'Stop Price',
        TradeInformation: 'Trade Information',
        isolated: 'isolated',
        OrderSize: 'Order Size',
        Available: 'Available',
        OrderBook: 'Order Book',
        Book: 'Book',
        Depth: 'Depth',
        Total: 'Total',
        Trading: 'Trading',
        Orders: 'Orders',
        Positions: 'Positions',
        Stops: 'Stops',
        History: 'History',
        PositionsHistory: 'Positions History',
        Please: 'Please',
        toStartTrading: 'to start trading',
        MarketPrice: 'Market Price',
        Action: 'Action',
        IsolatedMargin: 'Isolated Margin',
        CrossMargin: 'Cross Margin',
        LiqPrice: 'Liq. Price',
        ClosePosition: 'Close Position',
        Close: 'Close',
        SELL: 'SELL',
        BUY: 'BUY',
        ConfirmOrder: 'Confirm Order',
        Cancel: 'Cancel',
        Confirm: 'Confirm',
        OrderConfirmationTextMARKET: 'Are you sure to %side% %quantity% %symbol%?',
        OrderConfirmationTextLIMIT: 'Are you sure to place %side% %quantity% limit order on %symbol% with the price of %price%?',
        OrderConfirmationTextSTOP: 'Are you sure to place %side% %quantity% stop order on %symbol% with the price of %price%?',
        DontAsk: 'Don\'t ask next time'
    },
    ru: {
        companyName: 'bitjalang',
        Funding: 'Финансирование',
        in: 'через',
        SignIn: 'Войти',
        Equity: 'Средства',
        Locked: 'Заблокировано',
        MarginLevel: 'Уровень Маржи',
        Account: 'Аккаунт',
        SignOut: 'Выйти',
        ClientArea: 'Личный Кабинет',
        Profile: 'Профиль',
        Deposit: 'Депозит',
        Withdrawals: 'Выводы',
        Calculator: 'Калькулятор',
        ProfitLoss: 'Прибыль/Убыток',
        TargetPrice: 'Целевая Цена',
        LiquidationPrice: 'Цена Ликвидации',
        Side: 'Направление',
        Long: 'Покупка',
        Short: 'Продажа',
        Amount: 'Сумма',
        EntryPrice: 'Цена Входа',
        OpenPrice: 'Цена Открытия',
        ClosePrice: 'Цена Закрытия',
        CloseTime: 'Время Закрытия',
        Leverage: 'Плечо',
        Margin: 'Маржа',
        InitialQuantity: 'Стартовый Объем',
        FinalQuantity: 'Итоговый Объем',
        ROE: 'ROE',
        Cross: 'Кросс',
        Isolated: 'Изолированная',
        Balance: 'Баланс',
        CurrentMargin: 'Текущая Маржа',
        FinalMargin: 'Итоговая Маржа',
        Market: 'Рынок',
        Type: 'Тип',
        Price: 'Цена',
        Filled: 'Исполнено',
        Quantity: 'Объем',
        TimeExecuted: 'Время Исполения',
        Status: 'Статус',
        Prev: 'Пред',
        Next: 'След',
        LastTrades: 'Последние Сделки',
        All: 'Все',
        My: 'Мои',
        Time: 'Время',
        Login: 'Логин',
        Password: 'Пароль',
        Markets: 'Рынок',
        Instrument: 'Инструмент',
        LastPrice: 'Цена',
        Change: 'Изменение',
        Volume: 'Объем',
        NewOrder: 'Новый Ордер',
        Limit: 'Лимит',
        Stop: 'Стоп',
        StopPrice: 'Цена Стопа',
        TradeInformation: 'Информация о Сделке',
        isolated: 'изолированная',
        OrderSize: 'Объем Ордера',
        Available: 'Доступно',
        OrderBook: 'Книга Заявок',
        Book: 'Книга',
        Depth: 'Глубина',
        Total: 'Сумма',
        Trading: 'Торговля',
        Orders: 'Ордера',
        Positions: 'Позиции',
        Stops: 'Стопы',
        History: 'История',
        PositionsHistory: 'История Позиций',
        Please: 'Авторизуйтесь, ',
        toStartTrading: 'для начала торговли',
        MarketPrice: 'Рыночная Цена',
        Action: 'Действие',
        IsolatedMargin: 'Изолированная Маржа',
        CrossMargin: 'Кросс-Маржа',
        LiqPrice: 'Цена Ликв.',
        ClosePosition: 'Закрыть',
        Close: 'Закрыть',
        SELL: 'ПРОДАТЬ',
        BUY: 'КУПИТЬ',
        ConfirmOrder: 'Подтверждение',
        Cancel: 'Отмена',
        Confirm: 'Подтвердить',
        OrderConfirmationTextMARKET: 'Вы уверены, что хотите %side% %quantity% %symbol%?',
        OrderConfirmationTextLIMIT: 'Вы уверены, что хотите разместить лимитный ордер %side% %quantity% %symbol% по цене %price%?',
        OrderConfirmationTextSTOP: 'Вы уверены, что хотите разместить стоп-ордер %side%%quantity% %symbol% по цене %price%?',
        DontAsk: 'Не спрашивать в следующий раз'
    }
}

export default langs